name: CD - Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Gateway
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/Gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/urlshortener-gateway:latest

      - name: Build and push UrlShortenerService
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/Services/UrlShortenerService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/urlshortener-service:latest

      - name: Build and push RedirectService
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/Services/RedirectService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/redirect-service:latest

      - name: Build and push AnalyticsService
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/Services/AnalyticsService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/analytics-service:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./src/Frontend
          file: ./src/Frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/urlshortener-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/urlshortener
            git pull origin main
            docker-compose pull
            docker-compose up -d --build
            docker system prune -f
