name: Deploy to Railway

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy Gateway Service
        run: railway up --service=gateway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        working-directory: ./

      - name: Deploy URL Shortener Service
        run: railway up --service=urlshortener-service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        working-directory: ./

      - name: Deploy Redirect Service
        run: railway up --service=redirect-service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        working-directory: ./

      - name: Deploy Analytics Service
        run: railway up --service=analytics-service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        working-directory: ./

      - name: Deployment Complete
        run: echo "✅ All services deployed successfully to Railway!"
